version: "3"

services:
  coder:
    container_name: coder
    build: .
    ports:
      - 4200:4200
    env_file:
      - .coder.env
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./code:/code
    tty: true
